name: tryx_example
description: Example demonstrating the Tryx error handling library
publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  tryx:
    path: ../

dev_dependencies:
  lints: ^5.0.0
