name: tryx
description: A Dart library for functional, reliable, and expressive error handling.
version: 1.0.0
homepage: https://github.com/Liv-Coder/tryx
repository: https://github.com/Liv-Coder/tryx
issue_tracker: https://github.com/Liv-Coder/tryx/issues
documentation: https://pub.dev/documentation/tryx/latest/

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  meta: ^1.15.0

dev_dependencies:
  coverage: ^1.9.2
  lints: ^5.0.0
  test: ^1.24.0

# Funding information
funding:
  - https://github.com/sponsors/your-org

# Topics for pub.dev discoverability
topics:
  - error-handling
  - functional-programming
  - result-type
  - dart
  - flutter
  - safe-execution
  - exception-handling
